config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :searches
      resources :queries
      resources :pages
      resources :optimised_queries

      root to: "queries#index"
    end
  root to: 'application#index'
  get '/search', to: 'application#search'
  get '/articles', to: 'page#index', as: :pages
  get '/article/:id', to: 'page#show', as: :page
  get '/r', to: 'application#r'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/optimised_query.rb
class OptimisedQuery < ApplicationRecord
  validates :query_id, :weighting, :adgroup_id, presence: true
  belongs_to :query
  has_one :search, :through => :query

end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/query.rb
class Query < ApplicationRecord
  validates :query, :weighting, :search_id, presence: true

  belongs_to :search
  has_many :optimised_queries

  before_save :strip_query
  
  def rpc
    return nil
  end

  private

  def strip_query
    self.query_stripped = self.query.downcase.gsub(/\s+/, "").gsub("'", '')
  end


end

app/models/search.rb
class Search < ApplicationRecord
  validates :slug, presence: true
  has_many :queries
  has_many :optimised_queries, through: :queries
  accepts_nested_attributes_for :queries
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    http_basic_authenticate_with(
      name: Rails.application.credentials.production[:admin][:name],
      password: Rails.application.credentials.production[:admin][:password]
      )

    def index
      search_term = params[:search].to_s.strip
      resources = Administrate::Search.new(scoped_resource, dashboard_class, search_term).run
      # resources = order.apply(resources)
      resources = resources.page(params[:page]).per(records_per_page)
      page = Administrate::Page::Collection.new(dashboard)

      render locals: {
        resources: resources,
        search_term: search_term,
        page: page,
        show_search_bar: show_search_bar?,
      }
    end
  end
end

app/controllers/admin/optimised_queries_controller.rb
module Admin
  class OptimisedQueriesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Search.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Search.find_by!(adgroup_id: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/pages_controller.rb
module Admin
  class PagesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Search.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Search.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/queries_controller.rb
module Admin
  class QueriesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Query.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Query.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/searches_controller.rb
module Admin
  class SearchesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Search.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Search.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def index
    @pages = Page.all
    @slider = @pages[0..2]
    @sidebar = @pages[3..4]
    @grid = @pages[5..10]
  
  end

  def search
    extra_params = params
    extra_params.delete :controller
    extra_params.delete :action

    compact_params = { kv_delimiter: '__', pair_delimiter: '___', special_characters: {'.' => '_dot_'}}
    
    chnm = 'fb' if params[:utm_source] == 'facebook'
    chnm = 'gs' if params[:utm_source] == 'adwords'
    chnm = 'gdn' if params[:utm_source] == 'gdn'
    chnm = 'bing' if params[:utm_source] == 'bing'
    chnm = 'taboola' if params[:utm_source] == 'taboola'
    chnm = 'outbrain' if params[:utm_source] == 'outbrain'
    chnm3 = @gstats.compact(['source', 'campaign_id', 'project_id', 'adgroup_id'], **compact_params, hour: true)
    

    convtrack = {}
    convtrack[:properties_extra_value] = '0'
    convtrack[:id] = 'extid_1'
    convtrack_query = CGI.escape(convtrack.to_query)

    redirect_to("https://results.autospecsdirect.com/dynamiclander/?q=search&chnm=#{chnm}&chnm2=search&chnm3=#{chnm3}&convtrack=%26#{convtrack_query}&#{extra_params.to_query}") and return if params[:q].blank?

    search = Search.includes(:optimised_queries).find_by(slug: params[:q])

    optimised = search.optimised_queries.where(adgroup_id: params[:aid])
    defaults = search.optimised_queries.where(adgroup_id: 'default').where.not(query_id: optimised.pluck(:query_id))
    merged = optimised.or(defaults)


    if search.present?
      extra_params.delete :q

      if merged.count == 0
        optimised_query = _weighted_choice(search.queries)
      else
        optimised_query = _weighted_choice(merged)
        optimised_query = optimised_query.query
      end

      cpr = 0.0
      dcpr = 'd_15_0'
      cpr = (optimised_query.rpc * 15).round(2) unless optimised_query.rpc.nil?
      dcpr = "d_15_#{(optimised_query.rpc * 15).round(2)}" unless optimised_query.rpc.nil?
      
      convtrack[:properties_extra_value] = dcpr
      convtrack[:id] = "extid_#{params[:tracking_id]}" unless params[:tracking_id].nil?
      convtrack_query = CGI.escape(convtrack.to_query)  
            
      url = 'https://results.autospecsdirect.com/dynamiclander/'
      
      redirect_to("#{url}?p=#{search.p_val}&q=#{optimised_query.query}&chnm=#{chnm}&chnm2=#{optimised_query.query}&chnm3=#{chnm3}&cpr=#{cpr}&convtrack=%26#{convtrack_query}&#{extra_params.to_query}") and return
    else
      convtrack_query = CGI.escape(convtrack.to_query)  

      redirect_to("https://results.autospecsdirect.com/dynamiclander/?q=#{params[:q]}&chnm=#{chnm}&chnm2=#{params[:q]}&chnm3=#{chnm3}&convtrack=%26#{convtrack_query}&#{extra_params.to_query}") and return
    end
    
  end

  private

  def _weighted_choice(keywords)
    total = keywords.sum(:weighting)

    random = rand(1..100) / 100.0 * total
    keywords.each do |keyword|
      random -= keyword.weighting
      return keyword if random <= 0
    end
  end

end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
    @pages = Page.all
  end

  def show

    @page = Page.find(params[:id])

    # @browser = Browser.new(request.user_agent)
    # if @browser.device.mobile?
    #   feed = Skenzo.build.get_feed(@page.title, request.remote_ip, request.user_agent, request.original_url, request.referer, 1, 5, params, @gstats) 
    #   @ads = feed.Results.AdResultSet.Listing
    # end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_sidebar.html.erb
<aside class="sidebar row">
  <% @sidebar.each do |page| %>
    <a class="sidebar-link col-12 col-md-6 col-lg-12" href="<%= page_url(page) %>">
      <article class="sidebar-article">
        <div class="sidebar-image fill" style="background-image:url('<%= page.image_url %>');"></div>
        <span class="sidebar-date"><%= page.updated_at.strftime("%d %b, %Y") %></span>
        <h3><%= page.title %></h3>
      </article>
    </a>
  <% end %>
</aside>

app/views/application/_slider.html.erb
<div id="homeCarousel" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner" role="listbox">

    <% @slider.each_with_index do |page, index| %>
      <div class="carousel-item <%= index == 0 ? 'active' : '' %>">
        <a href="<%= page_url(page) %>" class="carousel-article-link">
          <article class="fill" style="background-image:url('<%= page.image_url %>');">
            <div class="carousel-caption-wrapper">
              <div class="carousel-caption text-center">
                <span class="caption-date"><%= page.updated_at.strftime("%d %b, %Y") %></span>
                <h1><%= page.title %></h1>
                <h3><%= page.subtitle %></h3>
              </div>
            </div>
          </article>
        </a>
      </div>

    <% end %>



    <ol class="carousel-indicators">
      <li data-target="#homeCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#homeCarousel" data-slide-to="1"></li>
    </ol>
  </div>
  <a class="carousel-control-prev" href="#homeCarousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#homeCarousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/application/index.html.erb
<section class="section-top row no-gutters">
  <div class="col-12 col-lg-8 col-xl-9">
    <%= render 'slider' %>
  </div>
  <div class="col-12 col-lg-4 col-xl-3">
    <div class="container">
      <%= render 'sidebar' %>
    </div>
  </div>
</section>
<section class="section-secondary">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-9 col-xl-8">
        <div class="text">
          <h2>Search Be, your place for information</h2>
          <p>
            Got something you need to know? Searching for answers is what we do best. Our team at autospecsdirect are constantly diving in to do the research and come up with the right information, helpful tips and important facts, so you can be well informed on your favourite topics. 
          </p>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="section-grid">
  <div class="container">
    <h2>Check Out More Articles</h2>
    <div class="row justify-content-center">

      <% @grid.each do |page| %>
        <a class="section-grid-link col-12 col-md-6 col-lg-4" href="<%= page_url(page) %>">
          <article class="section-grid-article">
            <div class="section-grid-image" style="background-image:url('<%= page.image_url %>');"></div>
            <span class="section-grid-date"><%= page.updated_at.strftime("%d %b, %Y") %></span>
            <h3><%= page.title %></h3>
          </article>
        </a>
      <% end %>

    </div>
  </div>
</section>

<!-- 

<body class="home-page">
  <header>
    <section class="search">
      <div class="container">
        <div class="logo">
          <%= image_tag 'autospecsdirect-logo.png' %>
        </div>
        <div class="search-bar">
          <form action="https://results.autospecsdirect.com/dynamiclander/" method="GET">
            <input type="text" name="q" id="search-input" value="">
            <button>
              <%= image_tag 'magnifier.png' %></button>
          </form>
        </div>
      </div>
    </section>
  </header>
  <footer>
    <nav>
      <div class="container">
        <div class="logo">
          <a target="_blank" href="/">
            <%= image_tag 'autospecsdirect-logo.png' %></a>
        </div>
        <a target="_blank" href="http://results.autospecsdirect.com/lgl/autospecsdirectcom_PrivacyPolicy.pdf">PRIVACY</a>
      </div>
    </nav>
  </footer>
</body> -->

app/views/fields/optimised_queries_field/_form.html.erb
<div class="field-unit__label">
  <%= f.label field.attribute %>
</div>
<div class="field-unit__field">
  <%= f.text_field field.attribute %>
</div>

app/views/fields/optimised_queries_field/_index.html.erb
<%= field.to_s %>

app/views/fields/optimised_queries_field/_show.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>

<% adgroup_ids = field.data.pluck(:adgroup_id).uniq %>

<% adgroup_ids.each do |adgroup| %>
  <hr>
  <h1 style="text-align: center;">adgroup: <%= adgroup %></h1>
  <canvas id="<%= adgroup %>" width="400" height="100"></canvas>
  <% oqs = field.data.where(adgroup_id: adgroup).order(weighting: :desc) %>
  <script>
  var ctx = "<%= adgroup %>";

  var myChart = new Chart(ctx, {
    type: 'pie',
    data: {
      labels: <%= raw(oqs.pluck(:query)) %>,
      datasets: [{
        data: <%= oqs.pluck(:weighting) %>,
        backgroundColor: ["#845ec2", "#2c73d2", "#d65eb1", "#ff7091", "#ff9671", "#ffc75f", "#fbeaff", "#018f7a", "#F9F871", "#08bee0", "#f9f5ff", "#67697c", "#fded86", "#dc965a", "#b79d94", "#eb8a40", "#b3b3b3", "#c74e29", "#9d4429", "#753c2c", "#4c3430"],
        borderWidth: 1
      }]
    },
    options: {
      rotation: 3,
    }
  });
  </script>
  <hr>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-xs-12">
        <%= image_tag 'autospecsdirect-logo.png', class: 'footer_logo', alt: '' %>
        <p class="copyright">&copy; Groovy Media <%= Time.now.year %></p>
      </div>
      <div class="col-md-6 col-xs-12 text-md-right">
        <ul class="footer-nav">
          <li class="align-middle"><%= link_to 'TERMS', 'http://privacy.autospecsdirect.com/terms', target: '_blank' %></li>
          <li class="align-middle"><%= link_to 'PRIVACY', 'http://privacy.autospecsdirect.com/privacy', target: '_blank' %></li>
          <li class="align-middle"><%= link_to 'CONTACT', 'http://privacy.autospecsdirect.com/contact-us', target: '_blank' %></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_head_scripts.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-16407288-28"></script>
<script async src="https://www.googletagmanager.com/gtag/js?id=AW-777281614"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-16407288-28');
  gtag('config', 'AW-777281614');
</script>

app/views/layouts/_top_nav.html.erb
<div>
  <div class="container border-bottom-0">
    <nav class="navbar navbar-light navbar-toggleable-md">
      <a class="navbar-brand" href="/">
        <img src="<%= asset_path 'autospecsdirect-logo.png' %>" class="navbar-logo">
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#dsNav" aria-controls="dsNav" aria-expanded="false" aria-label="Toggle navigation">
        <%= image_tag 'hamburger_mobile.png' %>
      </button>

      <div class="collapse navbar-collapse" id="dsNav">
        <ul class="navbar-nav ml-auto my-3">
          <li class="nav-item">
            <a class="nav-link" href="/">HOME</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="http://privacy.autospecsdirect.com/contact-us" target="_blank">CONTACT US</a>
          </li>
        </ul>
        <form action="https://results.autospecsdirect.com/dynamiclander/" method="get" class="form-inline mb-3 mb-lg-0 mt-md-0 SearchForm">
          <div class="input-group SearchForm__input-group">
            <input class="form-control SearchForm__search-box" type="text" placeholder="Search" name='q' value='<%= params[:q] %>' >
            <button class="btn btn-outline-primary input-group-addon SearchForm__button" type="submit" ><%= image_tag 'search-solid.svg', class: 'SearchForm__magnifying-glass' %></button>
          </div>
        </form>
      </div>
    </nav>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title.present? ? @page_title : 'autospecsdirect' %></title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="<%= image_path 'favicon.png' %>" rel="icon" type="image/png" />
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <%= render 'layouts/head_scripts' %>
  </head>
  <body>
    <%= render 'layouts/top_nav', cached: true %>
    <%= yield %>  
    <%= render 'layouts/footer', cached: true %>
  </body>
</html>

app/views/layouts/messages.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
      /* Email styles need to be inline */
    </style>
  </head>

  <body>
    Sent
  </body>
</html>

app/views/page/index.html.erb
<div class="container container-page">
  <div class="row">
    <div class="col-sm-12 col-md-3 pt-2">
      <div class="list-group">
        <% @pages.each do |p| %>
          <%= link_to p.title, page_path(p), class: "list-group-item" %>
        <% end %>
      </div>
    </div>
    <div class="col-sm-12 col-md-7 pt-2">
    </div>
  </div>
</div>

app/views/page/show.html.erb
<div class="container container-page">
  <div class="row">
    <div class="col-sm-12 pb-5">
      <h3><%= @page.title %></h3>
      <p><%= @page.body.html_safe unless @page.body.nil? %></p>
    </div>
  </div>
  <div class="gptslot" data-adunitid="0"></div>
</div>